added-hector-slam
husky/husky pull request #144
Opened 2020-09-28 11:18 UTC by basavarajnavalgund

## How to run frontier exploration with husky

To run **gazebo with spawned robot**

```
cd ~/catkin_ws/
roslaunch husky_gazebo husky_empty_world.launch
```	

To run **hector_slam_demo**

```
cd ~/catkin_ws
roslaunch husky_navigation hector_slam_demo.launch 
```

2020-09-28 14:27 UTC, tonybaltovski commented
@basavarajnavalgund `frontier_exploration` was removed since it was not released for melodic.  It can't be re-added till it gets bloomed.

2020-09-28 14:29 UTC, tonybaltovski requested changes

2020-09-28 14:29 UTC, tonybaltovski commented on .vscode/c_cpp_properties.json
> +{
Remove this please.

2020-09-28 14:29 UTC, tonybaltovski commented on .vscode/settings.json
> +{
Remove this please.

2020-09-28 23:42 UTC, tonybaltovski requested changes
This is missing a dependency on `hector_slam`  Again, frontier_exploration was removed since it was not released for melodic. It can't be re-added till it gets bloomed.

2020-09-29 08:18 UTC, basavarajnavalgund reviewed
> This is missing a dependency on `hector_slam` Again, frontier_exploration was removed since it was not released for melodic. It can't be re-added till it gets bloomed.

Ah okay when released for melodic we can add..
Added dependencies for hector_slam. Please check latest commit 15052639f9e54a421710f8c78423060f7fcb4be6

2020-09-29 08:18 UTC, basavarajnavalgund commented on .vscode/settings.json
> +{
Sure i'll do..

2020-09-29 08:18 UTC, basavarajnavalgund commented on .vscode/settings.json
> +{
Done i've removed... Please check my latest commit a97b15e67647e9121b43a79a7da7a19bce8dcb03

2020-09-29 08:18 UTC, basavarajnavalgund commented on .vscode/c_cpp_properties.json
> +{
Done i've removed.. Please check my latest commit a97b15e67647e9121b43a79a7da7a19bce8dcb03

2020-10-15 07:58 UTC, closed without merging