Update VLP16 mount URDF to better represent real-world
husky/husky pull request #194
Opened 2021-12-01 23:58 UTC by jyang-cpr

![mount1](https://user-images.githubusercontent.com/39268744/144333299-2dc6fe8e-e318-4873-b8c0-d87dd7196ff4.png)

2021-12-01 23:59 UTC, jyang-cpr commented
As per RPSW-1314

2021-12-06 20:34 UTC, civerachb-cpr requested changes

2021-12-06 20:34 UTC, civerachb-cpr commented on husky_description/urdf/accessories/vlp16_mount.urdf.xacro
> +      <origin xyz="0 0 ${height}" rpy="0 0 0"/>
Is there a reason to change this to not use the origin argument?  With these changes it looks like it's now impossible to move the assembly relative to the parent link in the X and Y directions, and it's impossible to rotate it.

2021-12-06 21:41 UTC, civerachb-cpr approved these changes

2021-12-06 21:50 UTC, merged