Properly support GX5
husky/husky pull request #77
Opened 2018-04-12 20:06 UTC by dniewinski

Updated udev rule to differentiate between the GX3 (legacy) and the GX5 (current) and install a different launch file

2018-04-12 22:10 UTC, tonybaltovski reviewed
Just minor nits.  Otherwise, LGTM.  Should to wait on the driver being released.

2018-04-12 22:10 UTC, tonybaltovski commented on husky_bringup/launch/microstrain_gx5_config/microstrain_gx5.launch
> +  <!-- For setting debug level to debug -->
Remove if not used?

2018-04-12 22:10 UTC, tonybaltovski commented on husky_bringup/launch/microstrain_gx5_config/microstrain_gx5.launch
> +  <!-- Diagnostics -->
Remove

2018-04-12 22:10 UTC, tonybaltovski commented on husky_bringup/package.xml
> +  <run_depend>microstrain_3dm_gx5_45</run_depend>
Hasn't been released for Kinetic https://github.com/bsb808/microstrain_3dm_gx5_45/issues/6.

2018-06-21 15:59 UTC, dniewinski commented on husky_bringup/package.xml
> +  <run_depend>microstrain_3dm_gx5_45</run_depend>
Poked again to have it released.  All other suggestions done

2018-10-25 12:46 UTC, dniewinski commented
Any movement on this?

2019-05-28 15:52 UTC, tonybaltovski commented
@dniewinski see comments.

2019-08-01 18:29 UTC, tonybaltovski requested changes

2019-08-01 18:29 UTC, tonybaltovski commented on husky_bringup/package.xml
> +  <run_depend>microstrain_mips5</run_depend>
@dniewinski typo

2019-08-01 18:42 UTC, merged